### ISSUE TITLE
Discuss the model to try on FPGA first

### ISSUE THREAD

**Issue by jerry20091103** [jerry20091103/23th-project#12]

**Comment by jerry20091103** [comment]
需要比較3個model的size (side by side)

**Comment by fann9876543210** [comment]
R2+1D
```
Total params: 31,342,704
Trainable params: 31,342,704
Non-trainable params: 0
Params size (MB): 125.37
```
```
Total mult-adds (G): 4.89
Input size (MB): 0.15
Forward/backward pass size (MB): 84.01
Estimated Total Size (MB): 209.53
```

------

TSM
```
Total params: 23,714,981
Trainable params: 23,714,981
Non-trainable params: 0
Params size (MB): 94.86
```
```
Total mult-adds (M): 635.36
Input size (MB): 0.08
Forward/backward pass size (MB): 25.60
Estimated Total Size (MB): 120.53
```

------

Rubiksnet

| Tier | Tiny | Tiny | Small | Small |
| -- | -- | -- | -- | -- |
| Variant | Rubiks3d-aq | rubiks3d | rubiks3d-aq | rubiks3d |
| num_frames | 8 | 8 | 8 | 8 |
| Params size(MB) | 7.24 | 7.21 | 13.72 | 13.67 |
| Input size (MB) | 9.19 | 9.19 | 9.19 | 9.19 |
| Forward backward pass size (MB) | 171.20 | 264.55 | 247.10 | 371.57 |
| Estimated Total Size (MB) | 187.63 | 280.94 | 270.01 | 394.43 |

| Tier | Medium | Medium | Large | Large |
| -- | -- | -- | -- | -- |
| Variant | Rubiks3d-aq | rubiks3d | rubiks3d-aq | rubiks3d |
| num_frames | 8 | 8 | 8 | 8 |
| Params size(MB) | 23.59 | 23.49 | 32.57 | 32.42 |
| Input size (MB) | 9.19 | 9.19 | 9.19 | 9.19 |
| Forward backward pass size (MB) | 294.16 | 469.87 | 375.55 | 614.57 |
| Estimated Total Size (MB) | 326.94 | 502.55 | 417.31 | 656.18 |
