### ISSUE TITLE
FIR python

### ISSUE THREAD

**Issue by plumy2828** [jerry20091103/23th-project#16]

**Comment by jerry20091103** [comment]
加上了FIR python的實作部分。
我有解釋整個python code在幹嘛， @jessie570314  可以看看，或許可以幫妳知道前面的fir spec要怎樣寫。有些s_axilite的control，或許前面的example 1 也會用到? @fann9876543210  @PaulWang0513  可以看看，看要不要要移到前面講?
有寫錯跟我說~

**Comment by jerry20091103** [comment]
![image](https://user-images.githubusercontent.com/56674403/180652375-85504b69-3500-4c3f-83b4-51fb75e50834.png)
還有這個address mapping不知道該放哪邊講

**Comment by jerry20091103** [comment]
Need to add code to compare the result of FIR IP against numpy results.
