### ISSUE TITLE
schedule viewer灰色的部分 operation 的數字是什麼意思，虛線的部分是什麼意義，為什麼會time violation

### ISSUE THREAD

**Issue by plumy2828** [jerry20091103/23th-project#23]

**Comment by plumy2828** [comment]
https://docs.xilinx.com/r/2021.2-English/ug1399-vitis-hls/Schedule-Viewer

**Comment by fann9876543210** [comment]
1. operation執行的時長
2. 第幾個clock cycle
3. data在傳輸前需要一段時間穩定才可以確保值是正確的，也會預留時間給後續的placing, routing
4. operation無法在虛線前完成，又必須傳輸的時候發生，可能會導致傳出的data出現錯誤

------

修改的部分
1. 加上schedule viewer的圖示說明
2. 將clock period從5改成10，修掉time violation的warning
