### ISSUE TITLE
image I/O interface & python code

### ISSUE THREAD

**Issue by fann9876543210** [jerry20091103/23th-project#25]

**Comment by jerry20091103** [comment]
input 32 int, output 120 int
The interface is done, The usage is the same as FIR example.
The file has been committed to this repo, just clone the repo to your computer and modify it directly.

**Comment by jerry20091103** [comment]
v2 bitfile and hwh file added to the repo.
The vivado project and vitis project can be opened with 2022.1 version

**Comment by plumy2828** [comment]
all pass.
python_v2 is added to the repo.
![image](https://user-images.githubusercontent.com/56674468/182010773-e10771b9-f3d6-4cc4-9e1b-a9fd38b18850.png)
