### ISSUE TITLE
change data type into precise bitwidth

### ISSUE THREAD

**Issue by fann9876543210** [jerry20091103/23th-project#29]
把int的type改掉了

**Comment by jessie570314** [comment]
把array分part設定不同的bitwidth並更改部分寫法
Latency: 2673->1599
FF: 17103->2683
LUT:33322->5452

之前的performance
<img width="242" alt="截圖 2022-08-03 下午5 48 58" src="https://user-images.githubusercontent.com/20158280/182579665-898c4c29-ec65-4d10-acdf-2788cb4047f3.png">


現在的

<img width="467" alt="截圖 2022-08-03 下午5 38 29" src="https://user-images.githubusercontent.com/20158280/182579264-e7380cc8-b2e3-4cfd-ba6a-75477f48e82d.png">

<img width="445" alt="截圖 2022-08-03 下午5 38 06" src="https://user-images.githubusercontent.com/20158280/182578658-02b9467f-fc52-43c0-ae28-33ce359de147.png">

**Comment by jerry20091103** [comment]
輸出out 的那個port也改成2bit會不會比較好?
但是和python 在相接的時候好像python沒有2bit int可以用，還是說output也換成8bit

合成完有測試計算的結果是對的嗎?

**Comment by jessie570314** [comment]
有做simulation/cosimulation都pass了，我會試試看換output，但out的port應該對utilization影響不大，因為他就只是用在最後的output，沒有參與中間的計算。

後來想到可能output的速度上會有差，我再試試看

**Comment by jessie570314** [comment]
修改多餘的乘法，把output減少到只輸出最後結果並且改成3-bit，修改多餘的輸入
latency:
1598->922
utilization:
FF：2683減少至2099
LUT：5452減少至4456
BRAM: 6減少到4
DSP：23增加到25
<img width="452" alt="截圖 2022-08-05 下午3 54 18" src="https://user-images.githubusercontent.com/20158280/183033023-bcb91940-9c6d-44cc-870d-e5051f89fdbd.png">

**Comment by jessie570314** [comment]
在main_v2.cpp我把第二層的陣列都捨去直接輸出結果，latency和utilization都有好一點，但不確定會不會反而讓for loop太複雜
<img width="447" alt="截圖 2022-08-05 下午7 29 04" src="https://user-images.githubusercontent.com/20158280/183069630-295393b9-2c1c-44e3-9647-904b300cc469.png">
