### ISSUE TITLE
stream python跑起來

### ISSUE THREAD

**Issue by plumy2828** [jerry20091103/23th-project#39]

**Comment by jerry20091103** [comment]
Streaming 成功跑起來了，之前會卡在
`ipDMAOut.recvchannel.wait()`
現在可以能成功跑完，但Python出來的結果都是0......   (sim和co-sim都有過)
```
hardware execution time: 0.008261442184448242 s
Python execution time: 0.013887882232666016 s
results are different!
index 0: 0 <-> 0
index 1: 0 <-> 1
index 2: 0 <-> 0
index 3: 0 <-> 0
index 4: 0 <-> 2
index 5: 0 <-> 1
index 6: 0 <-> 1
index 7: 0 <-> 0
index 8: 0 <-> 2
index 9: 0 <-> 2
index 10: 0 <-> 1
index 11: 0 <-> 0
index 12: 0 <-> 0
index 13: 0 <-> 2
index 14: 0 <-> 0
index 15: 0 <-> 0
index 16: 0 <-> 0
index 17: 0 <-> 2
index 18: 0 <-> 1
index 19: 0 <-> 0
index 20: 0 <-> 2
index 21: 0 <-> 1
index 22: 0 <-> 1
index 23: 0 <-> 2
index 24: 0 <-> 0
index 25: 0 <-> 1
index 26: 0 <-> 1
index 27: 0 <-> 0
index 28: 0 <-> 1
index 29: 0 <-> 1
```
跑起來的原因沒有確定，但我覺得是TLAST的問題，PYNQ document 的DMA部分有提到
[https://pynq.readthedocs.io/en/latest/pynq_libraries/dma.html?highlight=dma](https://pynq.readthedocs.io/en/latest/pynq_libraries/dma.html?highlight=dma)
> Note that the DMA expects any streaming IP connected to the DMA (write channel) to set the AXI TLAST signal when the transaction is complete. If this is not set, the DMA will never complete the transaction. This is important when using HLS to generate the IP - the TLAST signal must be set in the C code.

原先iris streaming的code在輸入和輸出分別開一個 value_t (`value8_t valTemp`和`value3_t valTemp`)
他們在不同scope，所以輸入傳完時，輸入端的valTemp.last會變成 1 (TLAST訊號變1)；輸出端和它沒關係，所以輸出的TLAST (valTemp.last) 永遠不會變1，所以DMA_out不知道IP做完了，在那邊wait。

在FIR的streaming那邊，因為輸入和輸出是共用同一個value_t，輸入傳完時last = 1，會順便帶到output (因為我們只有改valTemp.data，valTemp.last沒動)，所以會結束。

我猜是這樣啦，要不然卡在dma wait好像沒有更好的解釋...

目前的改法是把read, acc_zero, fc1, fc2, write都整合到一個大outer loop (loop過 inputNum)，然後共用一個value8_t，這樣寫以後要做read - calc - write的pipeline也比較好寫。但Python的輸出是錯的，大家可以再debug看看@@

新的bitfile是 iris_hls_stream_v3.bit

**Comment by jerry20091103** [comment]
輸出都是0的bug修掉了，問題出在 iris.h
`typedef ap_axiu<8,1,1,1> value8_t;`
axiu是unsigned...
axis才是signed
不知道為什麼這樣sim和co-sim都會過

目前改成
`typedef ap_axis<8,1,1,1> value8_t;`
