### ISSUE TITLE
find c++ ml library to do convolution, and try to put it on vitis

### ISSUE THREAD

**Issue by plumy2828** [jerry20091103/23th-project#40]

**Comment by fann9876543210** [comment]
pytorch in C++

**Comment by fann9876543210** [comment]
FINN
- resnet50 for Alveo U250 only
- https://github.com/Xilinx/finn-examples/tree/main/build

pytorch flow for Vitis AI
- https://github.com/Xilinx/Vitis-AI/tree/master/setup/mpsoc
- https://support.xilinx.com/s/article/Custom-OP-complete-example-design-for-Pytorch?language=en_US

**Comment by fann9876543210** [comment]
Above site using pre-trained xmodel

---

To train our model on Jupyter notebook
-  compile with DPU
- https://github.com/Xilinx/DPU-PYNQ/blob/master/host/train_mnist_model.ipynb
