### ISSUE TITLE
Run iris on zynq zcu104

### ISSUE THREAD

**Issue by PaulWang0513** [jerry20091103/23th-project#41]
try to run iris model one zynq zcu104

**Comment by PaulWang0513** [comment]
encounter some problem
same code works on PYNQ-Z2, but error occur on ZCU104
try to solve later

![image](https://user-images.githubusercontent.com/65814684/184109677-e0340a1a-eb0d-4686-a094-0f323324d7e0.png)

**Comment by jerry20091103** [comment]
[https://pynq.readthedocs.io/en/latest/getting_started/zcu104_setup.html#zcu104-board-setup](https://pynq.readthedocs.io/en/latest/getting_started/zcu104_setup.html#zcu104-board-setup)
This?

**Comment by PaulWang0513** [comment]
Seems like I tried to use IP for Z2 on ZCU-104.
=> Try to generate the IP for ZCU-104, but stuck at block design

**Comment by PaulWang0513** [comment]
Successfully generate bit file for lab1 (mul2num), and run on zcu104!
The encountered problem can be solved by running "Generate Output Products" before "Create HDL Wrapper".
![image](https://user-images.githubusercontent.com/65814684/184993071-15086ad0-a87f-49f1-ac3f-55568395744b.png)

Trying iris...

**Comment by PaulWang0513** [comment]
Successfully run iris (memory-mapped version) on zcu104!

In block design, change configuration of MPSoC from
![image](https://user-images.githubusercontent.com/65814684/184984884-c40bb264-151b-46ed-92c1-2df9cc641a0d.png)
to
![image](https://user-images.githubusercontent.com/65814684/184984938-83394a21-98fc-4789-9f61-f7a6fceadcee.png)

**Comment by PaulWang0513** [comment]
Keep working on stream version

**Comment by PaulWang0513** [comment]
done
