### ISSUE TITLE
R2+1D python每一層，拿來做我們自己寫的IP驗證

### ISSUE THREAD

**Issue by plumy2828** [jerry20091103/23th-project#48]

**Comment by jessie570314** [comment]
https://colab.research.google.com/drive/1yykTdfRAIax310-U8H79oBoeog8ToDSY#scrollTo=c3GT9qpDmqaU

python code for resnet built with r2+1d layers

reference:
https://github.com/irhum/R2Plus1D-PyTorch
https://github.com/pytorch/vision/blob/9e474c3c46c0871838c021093c67a9c7eb1863ea/torchvision/models/video/resnet.py#L324
https://github.com/jfzhang95/pytorch-video-recognition/blob/master/network/R2Plus1D_model.py

**Comment by plumy2828** [comment]
1.找一組data，生出一層的答案
2.完成C++ testbench

**Comment by jessie570314** [comment]
完成第一層layer的data
