### ISSUE TITLE
R2+1D 一層(我們自己寫IP)

### ISSUE THREAD

**Issue by plumy2828** [jerry20091103/23th-project#49]

**Comment by plumy2828** [comment]
https://cpp.hotexamples.com/site/file?hash=0xfd8f5591aa0878aceabe4061fe804976cbefb8d273c70757fd494b9d202d7675&fullName=polybenchGpu-master/polybenchCodesCudaOpenClHMPPOpenAcc/HMPP/threedconv.c&project=lnangong/polybenchGpu

**Comment by fann9876543210** [comment]
https://github.com/madhur13490/PolybenchGPU/blob/master/OpenCL/3DCONV/3DConvolution.c

**Comment by plumy2828** [comment]
1.確認3D padding跟stride維度
2.把目前幾個小layer合成一個基本block

**Comment by fann9876543210** [comment]
R2Plus1dStem layer pass synthesis

synthesis report:
<img width="856" alt="image" src="https://user-images.githubusercontent.com/67409874/189394699-b8eda954-ce1b-4820-90b1-9c7488fbfce9.png">

**Comment by plumy2828** [comment]
解決simulation error，確認weight的size

**Comment by plumy2828** [comment]
已跑完全部第一層，我們的答案與golden誤差在小數點後五位

**Comment by fann9876543210** [comment]
update synthesis report
<img width="870" alt="image" src="https://user-images.githubusercontent.com/67409874/189541614-c374ddd6-3420-4d37-9887-7939417c5e82.png">

**Comment by jerry20091103** [comment]
把Interface直接加到r2plus1d.cpp上面了，四個io都是用axi memroy-mapped
目前效能應該蠻差的，建議輸入要先讀進buffer裡面，它才可以合成出burst的東西。weight到時候也可以直接死在ip裡
不過只是測試正確性效能應該沒差啦，IO的優化之後再慢慢做
