### ISSUE TITLE
run rubiksnet

### ISSUE THREAD

**Issue by plumy2828** [jerry20091103/23th-project#5]
- 在處理CUDA安裝問題(目前是10.0，要更新到10.1)

**Comment by jessie570314** [comment]
我現在的error
<img width="1074" alt="截圖 2022-07-23 下午2 18 16" src="https://user-images.githubusercontent.com/20158280/180593093-28f29576-bef4-40b0-8ced-3fbb2c6d1cd5.png">
這裡面應該是這一步錯
<img width="1018" alt="截圖 2022-07-23 下午2 21 45" src="https://user-images.githubusercontent.com/20158280/180593178-a4c3bb73-aa6e-47fe-9489-53f074ad6157.png">

**Comment by jessie570314** [comment]
我的colab連結
[https://colab.research.google.com/drive/1DT36wA-n4znpKajCHPznL0eLO91aL7Kb?usp=sharing](url)

**Comment by jessie570314** [comment]
model size如下，之後會再整理一下

RubiksNet-Large variant "rubiks3d". num_frames=8
tier=large batch=8 input=(2,8,3,224,224)

Total params: 8,421,522
Trainable params: 8,421,522
Non-trainable params: 0
Input size (MB): 73.50
Forward/backward pass size (MB): 4916.57
Params size (MB): 32.13
Estimated Total Size (MB): 5022.19


RubiksNet-Tiny variant "rubiks3d". num_frames=8
tier=tiny batch=8 input=(2,8,3,224,224) variant=rubiks3d
Total params: 1,889,040
Trainable params: 1,889,040
Non-trainable params: 0
Input size (MB): 73.50
Forward/backward pass size (MB): 2116.37
Params size (MB): 7.21
Estimated Total Size (MB): 2197.08



RubiksNet-Large variant "rubiks3d-aq". num_frames=8
tier=large batch=8 input=(2,8,3,224,224) variant=rubiks3d-aq
Total params: 8,536,782
Trainable params: 8,536,782
Non-trainable params: 0
Input size (MB): 73.50
Forward/backward pass size (MB): 3004.43
Params size (MB): 32.57
Estimated Total Size (MB): 3110.49



RubiksNet-Large variant "rubiks3d". num_frames=8
pretrained ssv2_large.pth.tar

Total params: 8,497,686
Trainable params: 8,497,686
Non-trainable params: 0
Input size (MB): 73.50
Forward/backward pass size (MB): 4916.58
Params size (MB): 32.42
Estimated Total Size (MB): 5022.49

**Comment by jessie570314** [comment]
<img width="498" alt="截圖 2022-07-26 下午8 43 30" src="https://user-images.githubusercontent.com/20158280/181008588-ea4aa27b-ce94-4138-b4ac-60d0a6235d01.png">
<img width="490" alt="截圖 2022-07-26 下午8 43 44" src="https://user-images.githubusercontent.com/20158280/181008630-bdae0189-61d9-4bd1-b631-d989899c8885.png">

**Comment by jessie570314** [comment]
batch=1

Tier | Tiny | Tiny | Small | Small
-- | -- | -- | -- | --
Variant | Rubiks3d-aq | rubiks3d | rubiks3d-aq | rubiks3d
num_frames | 8 | 8 | 8 | 8
Params size(MB) | 7.24 | 7.21 | 13.72 | 13.67
Input size (MB) | 9.19 | 9.19 | 9.19 | 9.19
Forward backward pass size (MB) | 171.20 | 264.55 | 247.10 | 371.57
Estimated Total Size (MB) | 187.63 | 280.94 | 270.01 | 394.43




Tier | Medium | Medium | Large | Large
-- | -- | -- | -- | --
Variant | rubiks3d-aq | rubiks3d | rubiks3d-aq | rubiks3d
num_frames | 8 | 8 | 8 | 8
Params size(MB) | 23.59 | 23.49 | 32.57 | 32.42
Input size (MB) | 9.19 | 9.19 | 9.19 | 9.19
Forward backward pass size (MB) | 294.16 | 469.87 | 375.55 | 614.57
Estimated Total Size (MB) | 326.94 | 502.55 | 417.31 | 656.18
