### ISSUE TITLE
Connect the camera and IP interface together.

### ISSUE THREAD

**Issue by jerry20091103** [jerry20091103/23th-project#52]

**Comment by PaulWang0513** [comment]
可以做real time 的顯示了，但大概只有4~5 fps，再看看能不能提升

**Comment by jerry20091103** [comment]
圖片IO的測試IP已經整理上去了，放在imageIO_test_hls 資料夾裡面。
附的v2 bitstream已經確定在Z2上可以跑，有一張DSC09011_112p.png可以在Python內demo測試用。

看要不要把相機先接在Z2上測試?這樣就不用重燒bit file

**Comment by PaulWang0513** [comment]
在Z2上成功！

目前體感大概有0.2秒的延遲，目前傳進IP的畫面是用原始畫面左上角的112x112 pixel，我再處理一下。
notebook 已上傳

**Comment by jerry20091103** [comment]
> 目前傳進IP的畫面是用原始畫面左上角的112x112 pixel

OpenCV 的capture好像可以用.set() 來設定解析度的樣子?

**Comment by PaulWang0513** [comment]
weird
![image](https://user-images.githubusercontent.com/65814684/189477850-7c9ee2db-6f57-49e4-9493-48ce53a0705f.png)

**Comment by PaulWang0513** [comment]
成功移植到ZCU104，就結論來說也畫面也很順暢！

奇怪的是，當開啟相機時用了不同編號(0 or -1)，解析度及FPS會有不同 (如圖)
![image](https://user-images.githubusercontent.com/65814684/189716989-2c8b00a5-34ee-4a7a-8baa-f201095f639c.png)
我嘗試在用0開啟時，用cap.set(...)調整解析度及FPS，但不知道是他有特定的規格或是其他原因，目前沒有成功。
所以現在是用-1開啟，畫面是順暢的
