### ISSUE TITLE
Resolve Sequential layer

### ISSUE THREAD

**Issue by fann9876543210** [jerry20091103/23th-project#53]

**Comment by jerry20091103** [comment]
https://arxiv.org/abs/1711.11248v3  R2+1D website

**Comment by fann9876543210** [comment]
https://github.com/pytorch/vision/blob/9e474c3c46c0871838c021093c67a9c7eb1863ea/torchvision/models/video/resnet.py#L81

**Comment by jerry20091103** [comment]
Sequential
https://pytorch.org/docs/stable/generated/torch.nn.Sequential.html#sequential
