### ISSUE TITLE
Simulation error percentage

### ISSUE THREAD

**Issue by fann9876543210** [jerry20091103/23th-project#57]

**Comment by jerry20091103** [comment]
Error percentage 已加入，計算方法是 `abs(output - golden) / golden`
少數結果有大於0.5%的誤差，這些結果大多都是答案數值特別小的 (ex. 0.001之類的)
這邊沒辦法給出確切數據， 因為我同樣的code在2022.1重跑simulation後，就跑不出來了...原因不明。
情形一樣是hang在 `Generating csim.exe` 那邊。
