### ISSUE TITLE
Implement More R2+1D Layer！！！

### ISSUE THREAD

**Issue by fann9876543210** [jerry20091103/23th-project#58]

**Comment by fann9876543210** [comment]
完成sequential layer 1~4，還需要data來驗證正確性

**Comment by plumy2828** [comment]
這週目標: 測試sequential layer 1

**Comment by jessie570314** [comment]
https://colab.research.google.com/drive/1yykTdfRAIax310-U8H79oBoeog8ToDSY#scrollTo=c3GT9qpDmqaU

**Comment by plumy2828** [comment]
目前跑起來了，但是誤差非常大。
有把log檔push上去了
不確定是不是我們就不該忽略之前的小誤差。
因為sequential layer本身沒有新的algorithm，只是把之前的Conv3、BatchNorm3d、ReLU做組合
但目前也不知道誤差產生的原因。

**Comment by fann9876543210** [comment]
Conv2+1d應該是沒問題了，之前是testbench的kernel抓錯值(index沒有從0開始算)
但BatchNorm3d的影響似乎有點大

目前只跑一層Conv2+1d之後的error rate是0.213249%
再跑他後一層BatchNorm3d之後的error rate就變成12.372948%了
詳細的simulation report我都放在資料夾裡面了

跑過一個BasicBlock的error rate是18.757473%
完整跑完Sequential_layer1(3個一模一樣的BasicBlock)的error_rate是87.324615% ......

資料我是用寫在我colab的檔重生過的，但因為中間一直改，檔名也是我亂取的就沒有push上去了
https://colab.research.google.com/drive/1BY2jyu7_5NfBomK_VPusbMld6_Euzgjm#scrollTo=AauOZAgDCcH2

---

也有姑且先跑了一下Sequential_layer1的synthesis report，但因為error還很大，就沒繼續把他變成bitstream了
<img width="864" alt="image" src="https://user-images.githubusercontent.com/67409874/191828395-d96d3783-25b8-4a1c-8e86-6a97efdb2e3f.png">
