### ISSUE TITLE
去查怎麼把現在code改成使用DRAM的寫法

### ISSUE THREAD

**Issue by plumy2828** [jerry20091103/23th-project#60]

**Comment by jerry20091103** [comment]
PS side RAM as a buffer for PL is verified to be working on Z2.
The `imageIO_RAM` folder contains all the sources and bit file for Z2.
This dummy test IP splits an 112x112 image into three components (R, G, B). The three components are stored in PS RAM buffer, then they are re-combined as a whole image.
