### ISSUE TITLE
quantize 整個r2+1d!!!!

### ISSUE THREAD

**Issue by plumy2828** [jerry20091103/23th-project#61]

**Comment by jessie570314** [comment]
成功quantize學長給的model

<img width="218" alt="截圖 2022-09-23 下午11 39 01" src="https://user-images.githubusercontent.com/20158280/191999295-c98ab294-ae6c-4534-9841-ee1a8bea6148.png">
<img width="249" alt="截圖 2022-09-23 下午11 39 24" src="https://user-images.githubusercontent.com/20158280/191999354-7dbfbc0d-49c9-4e7c-9054-a3f8ada08e5b.png">
還未測試quantize後的accuracy和拿出weight

**Comment by jessie570314** [comment]
quantize後的model跑學長之前給的demo影片沒有問題，但是跑我們自己做的圖片data準確度很低，還在檢查是什麼原因

**Comment by jessie570314** [comment]
Quantize 前的model準確度就只有18/50，Quantize 後下降到15/50

**Comment by jessie570314** [comment]
quantize過後的weight和30個影片的activation放在雲端的R2+1D 10 gestures資料夾(parameter.zip)
https://drive.google.com/drive/u/1/folders/1kKsgJ7GRyfuJp4mZARprEj4Sb5kJBfIl
之前報告的accuracy有經過fusion的步驟，但是因為fusion需要再改batchnorm的寫法，所以我先把這一步拿掉之後有餘力再做。
現在的accuracy:

<img width="399" alt="截圖 2022-10-18 下午11 50 20" src="https://user-images.githubusercontent.com/20158280/196480441-0d77b8c7-c6f9-4e13-9847-1ce13d38599f.png">
