### ISSUE TITLE
train data+準備data

### ISSUE THREAD

**Issue by plumy2828** [jerry20091103/23th-project#62]

**Comment by PaulWang0513** [comment]
Some training data of number 1\~5 is uploaded, and placed in /R2+1D/training_data/data_1_to_5.
In the folder, `class.txt` map the the exist classes and its idx.
There are 50 sub-folders (0\~49) in data_1_to_5, each containing 1 `label.txt` and 50 frames (0~49.jpg). 
Frames in a folder build an action. Content of `label.txt` shows which action happens in the corresponding frame (note that frames and labels are 0-index)

**Comment by jessie570314** [comment]
https://drive.google.com/drive/folders/0Bw5SwfZ-YKuTWThkSUg0U0ktRGM?amp%3Busp=sharing&resourcekey=0-vIB1r0zxBimdeU_l9MWG8A

**Comment by jessie570314** [comment]
完成下載資料到硬碟

**Comment by jerry20091103** [comment]
[https://stackoverflow.com/questions/25010369/wget-curl-large-file-from-google-drive](https://stackoverflow.com/questions/25010369/wget-curl-large-file-from-google-drive)
裡面有提到下載google drive的工具
但不管怎樣試都是access denied...

我看了一下，專題機的home directory是hdd，/dataset和/data是ssd，但我們似乎沒有/dataset, /data的權限，所以上面是嘗試下載在home directory裡面

**Comment by jerry20091103** [comment]
下載完成，放在 /data/RS_v1_50 裡面
