### ISSUE TITLE
改ide跑testbench

### ISSUE THREAD

**Issue by plumy2828** [jerry20091103/23th-project#65]

**Comment by jerry20091103** [comment]
成功讓batchnorm的結果一樣了
目前在testbench_batchnorm / testbench_copy 的結果無論在vitis / VS 都一樣
原因似乎是batchNorm的mu / var 沒有初始化...
![image](https://user-images.githubusercontent.com/56674403/197997701-4a1ad0ca-a5c9-4d09-8a7c-5a5cbfac62db.png)

**Comment by jerry20091103** [comment]
double 版的sequential_testbench layer 1在visual studio跑起來了，結果是這樣，似乎很不錯
![image](https://user-images.githubusercontent.com/56674403/197997915-00f791b7-9b93-4341-a733-df4d56c0bab2.png)
需要更改vs的heap size / stack size才可以跑
conv2plus1d的大陣列也換成malloc/free了
sequential.cpp有沒free的陣列也改掉了
